version: "0.2"
language: en
dictionaries:
  - en_US
  - softwareTerms
  - node
  - npm
  - html
  - css
  - bash
ignorePaths:
  - node_modules/**
  - build/**
  - package-lock.json
  - "**/*.svg"
  - "**/*.json"
words:
  - endusers
  - Docusaurus
  - docusaurus
  - Kubestellar
  - kubestellar
  - KubeCon
  - CloudNativeCon
  - cncf
  - CNCF
  - Cartografos
  - cartografos
  - Swisscom
  - Flipkart
  - Zeiss
  - Adobe
  - Allianz
  - CERN
  - roadmap
  - devcontainer
  - npx
  - mjs
  - frontmatter
  - sidebars
  - cspell
  - markdownlint
  - Prettier
  - prettier
  - AUSF
  - Aditya
  - Alertmanager
  - Bootc
  - bootc
  - bootstrappable
  - CNIP
  - CNOE
  - CNPG
  - Crossplane
  - Dapr
  - Dashboarding
  - Flexboxes
  - Flexperience
  - Hashith
  - KCSP
  - Karthik
  - Katib
  - Khushi
  - Kserve
  - kserve
  - Kubebuilder
  - Kubeflow
  - kubeflow
  - Kubermatic
  - Kubevirt
  - kubevirt
  - Kueue
  - Kyverno
  - kyverno
  - MGMT
  - MPLS
  - NETCONF
  - NSSF
  - NUMA
  - ONNX
  - Organisation
  - organisation
  - organised
  - PAGT
  - RAPL
  - RDMA
  - Redirector
  - Relocator
  - Rollouts
  - rollouts
  - Romande
  - Runbooks
  - runbooks
  - SDLC
  - SLURM
  - SNSSAI
  - snssai
  - Satchitanand
  - Telco
  - telco
  - Tiwari
  - Traefik
  - VRRP
  - Virt
  - behaviour
  - castrojo
  - centralised
  - chargeback
  - containerd
  - containerssh
  - coredns
  - criu
  - daemonset
  - dashboarded
  - dcgm
  - docus
  - dranet
  - enduser
  - externaldns
  - fintech
  - firewalling
  - gppnetwork
  - gprs
  - hackathons
  - hyperscalers
  - kubelet
  - lifecycles
  - maximise
  - metallb
  - minimise
  - multitenancy
  - multitenant
  - pcpus
  - rearchitecture
  - reimplementation
  - roadmaps
  - sdcio
  - stargz
  - tentpole
  - tolerations
