// End-to-end coverage for the two empty-corpus arms of
// src/components/CaseStudies/index.js, which need a build of their own.
//
// The component reads data/case-studies.json at module scope and branches on
// two document-level fields:
//
//   line 46  `if (!data.generatedAt) return null;` — SyncStatus renders no
//            provenance line when the corpus carries no generatedAt;
//   line 64  `const caseStudies = data.caseStudies || [];` — the `|| []`
//            fallback supplies the list the page sorts, filters, counts and
//            maps over when the corpus carries no caseStudies array at all.
//
// Neither arm is reachable against the data the site ships: the checked-in
// corpus always has a generatedAt and a full table of studies. Both are
// ordinary shapes rather than defensive dead code — the file is regenerated by
// `npm run collect:case-studies` (scripts/collect-case-studies.mjs) against
// cncf.io, so a collector run that fetches nothing is exactly what produces
// them.
//
// This is not a case tests/e2e/data-fixtures.spec.js can take. That file
// covers the branches an *additive* overlay reaches, where an extra record
// renders beside the real ones and nothing already covered stops rendering —
// which is what tests/e2e/fixtures/data/case-studies.json does for this same
// component, appending two undated studies so the comparator's `|| ''` arms
// and the empty date cell render. These two arms are the opposite: clearing
// the fields in the ordinary coverage build would trade the provenance line
// and every row, those two appended rows included, for them. They belong to
// the variant build for the same reason RadarReports' empty-corpus arms and
// AwardsTimeline's provenance paragraph do — see the preamble of
// tests/e2e/data-variants.spec.js for the mechanism.
// `npm run build:e2e:coverage` compiles a second site under
// /e2e-coverage-variant/ with tests/e2e/fixtures/data-variant/** layered on,
// one `docusaurus serve` offers both, and the report unions what each build
// reached.
//
// The real route is asserted alongside the variant one. On its own, an
// assertion that the variant page has no provenance line and no rows passes
// just as well when the page failed to build or the route is wrong; pairing it
// with the real route is what makes the pair evidence that the arms
// *switched*.
//
// What this does NOT do, yet: move the two regions out of the e2e report's
// uncovered list. The browser takes both arms — the assertions below only pass
// if it did — but tests/tools/e2e-coverage-report.mjs keys a region on its
// exact original `line:column:endLine:endColumn`, and the two builds' generated
// code maps back to different coordinates, so the union keeps the real build's
// zeros. That is the region-attribution problem tracked in #1066 and #1079,
// measured on this same shape in #1097; it is not something this fixture can
// reach, and once the union folds the coordinates these two arms fold with no
// change here.
import { test, expect } from '../tools/e2e-coverage.cjs';
import { loadSiteData } from '../tools/e2e-data-fixtures.cjs';

const CASE_STUDIES_PATH = '/resources/case-studies';
const VARIANT_BASE = '/e2e-coverage-variant';
const SECTION_NAME = 'CNCF case studies';
const PROVENANCE = /Mirrored from/;

// The variant site is only built by the coverage run; outside it the base
// path does not exist and the ordinary page still has a full corpus.
const describeCoverage =
  process.env.E2E_COVERAGE === '1' ? test.describe : test.describe.skip;

const COVERAGE_ENV = { E2E_COVERAGE: '1' };
const VARIANT_ENV = { E2E_COVERAGE: '1', E2E_COVERAGE_BUILD: 'variant' };

// Read the corpus through the overlay rather than hard-coding a count, so an
// edited overlay fails here instead of leaving a test that asserts nothing.
const studies = loadSiteData('case-studies.json', COVERAGE_ENV);
const variantStudies = loadSiteData('case-studies.json', VARIANT_ENV);

const sectionOf = (page) => page.getByRole('region', { name: SECTION_NAME });

describeCoverage('a case-study corpus the collector has not filled yet', () => {
  test('the real page dates its provenance line and lists its studies', async ({
    page,
  }) => {
    // The premise of the whole file: against the data the site ships, both
    // arms below are unreachable.
    expect(studies.generatedAt).toBeTruthy();
    expect(studies.caseStudies.length).toBeGreaterThan(0);

    await page.goto(CASE_STUDIES_PATH);
    const section = sectionOf(page);
    await expect(section).toBeVisible();
    await expect(section.getByText(PROVENANCE)).toBeVisible();
    await expect(section.locator('tbody tr')).toHaveCount(
      studies.caseStudies.length,
    );
    // No filters are set on load, so the results bar reports the whole corpus
    // on both sides — the denominator is `caseStudies.length` straight from
    // the array the `|| []` fallback did not have to supply.
    await expect(
      section.getByText(/Showing \d+ of \d+ case studies/),
    ).toHaveText(
      `Showing ${studies.caseStudies.length} of ${studies.caseStudies.length} case studies`,
    );
    await expect(
      section.getByText('No case studies match those filters.'),
    ).toHaveCount(0);
  });

  test('the variant page drops the provenance line and renders an empty table', async ({
    page,
  }) => {
    expect(variantStudies.generatedAt).toBeNull();
    expect(variantStudies.caseStudies).toBeNull();

    await page.goto(`${VARIANT_BASE}${CASE_STUDIES_PATH}`);
    // The route built and served: the page's own heading is prose around the
    // component, so it renders whether or not the corpus has anything in it.
    await expect(
      page.getByRole('heading', { name: 'Case Studies', level: 1 }),
    ).toBeVisible();
    const section = sectionOf(page);
    // The section itself still renders, with its toolbar and table head, so
    // this is the provenance line being absent and the body being empty rather
    // than the page failing to build.
    await expect(section).toBeVisible();
    await expect(section.getByText(PROVENANCE)).toHaveCount(0);
    await expect(
      section.getByLabel('Search case studies by organization'),
    ).toBeVisible();
    await expect(section.getByRole('columnheader')).toHaveCount(6);

    // `|| []` is what keeps `.sort`, `.filter`, `.length` and `.map` off a
    // null. Every one of those four reads is evidence the fallback supplied a
    // list: a zero row count comes from the map, the "0 of 0" from the two
    // lengths, and the empty state from the filtered array existing at all.
    await expect(section.locator('tbody tr')).toHaveCount(0);
    await expect(
      section.getByText(/Showing \d+ of \d+ case studies/),
    ).toHaveText('Showing 0 of 0 case studies');
    await expect(
      section.getByText('No case studies match those filters.'),
    ).toBeVisible();

    // The three selects are built from the same empty list, so each keeps only
    // its "All …" placeholder. This is the useCaseStudyFilterOptions path over
    // the fallback array rather than over the corpus.
    for (const label of [
      'Filter by CNCF project',
      'Filter by industry',
      'Filter by country',
    ]) {
      await expect(section.getByLabel(label).locator('option')).toHaveCount(1);
    }
  });
});
