// End-to-end coverage for the five empty-collection fallbacks in
// src/components/MetricsDashboard/index.js, which need a build of their own.
//
// The component reads data/metrics.json at module scope and maps over five
// document-level collections through a fallback that supplies an empty one:
//
//   line  65  `(lifecycle?.cards || []).map(...)`        — the lifecycle cards;
//   line  76  `Object.entries(lifecycle?.trends || {})`  — the trend grid;
//   line  85  `(lifecycle?.omitted || []).map(...)`      — the "what is not yet
//             measurable" disclosure items;
//   line 124  `Object.entries(metricsData.series || {})` — the line charts;
//   line 174  `Object.entries(metricsData.breakdowns || {})` — the bar charts.
//
// None of the five fallbacks is reachable against the data the site ships: the
// checked-in document always carries four cards, two trends, three omitted
// indicators, two series and two breakdowns. They are ordinary shapes rather
// than defensive dead code — metrics.json is regenerated by `npm run
// collect:metrics`, and a collector run that cannot reach one of its sources
// emits the document without that collection.
//
// This is not a case tests/e2e/data-fixtures.spec.js can take. That file
// covers the branches an *additive* overlay reaches, where an extra record
// renders beside the real ones and nothing already covered stops rendering.
// These five are the opposite: emptying the collections in the ordinary
// coverage build would trade every rendered card, trend, disclosure item, line
// chart and bar chart for the fallback, so the arms beside them would go
// uncovered instead. They belong to the variant build for the same reason
// AwardsTimeline's provenance paragraph does — see the preamble of
// tests/e2e/data-variants.spec.js for the mechanism. `npm run
// build:e2e:coverage` compiles a second site under /e2e-coverage-variant/ with
// tests/e2e/fixtures/data-variants/** layered on, one `docusaurus serve`
// offers both, and the report unions what each build reached.
//
// `referenceArchitectureLifecycle.trends` at line 76 used to be the one
// collection this overlay could not clear. The same overlay appended a point
// to `trends.submissions.values` for the single-point sparkline arm, `set` is
// applied before `append` in tests/tools/e2e-data-fixtures.cjs, and clearing
// trends would have made that append fail the build. That conflict is gone:
// the single-point trend is now `add`ed beside the real two in the ordinary
// build (tests/e2e/fixtures/data/metrics.json, asserted by
// tests/e2e/metrics-sparkline.spec.js), so nothing in the variant build needs
// trends to survive and line 76 is cleared here with the rest.
//
// The real route is asserted alongside the variant one. On its own, an
// assertion that the variant page renders no charts passes just as well when
// the page failed to build or the route is wrong; pairing it with the real
// route is what makes the pair evidence that the arms *switched* rather than
// that one page happens to look a certain way.
//
// What this does NOT promise: that the five regions leave the e2e report's
// uncovered list. The browser demonstrably takes the fallbacks — the
// assertions below only pass if it did — but
// tests/tools/e2e-coverage-report.mjs keys a region on its exact original
// coordinates, and the two builds' generated code does not always map back to
// the same ones. Where it does, the regions fold (the variant's cleared
// `generatedAt` already folds ReferenceArchitectures' two arms); where it does
// not, the union keeps the zero. That is the region-attribution problem
// tracked in #1066 and #1079, not something this fixture can reach.
import { test, expect } from '../tools/e2e-coverage.cjs';
import { loadSiteData } from '../tools/e2e-data-fixtures.cjs';

const METRICS_PATH = '/metrics';
const VARIANT_BASE = '/e2e-coverage-variant';
const LIFECYCLE = 'section[aria-labelledby="lifecycle-title"]';
const CARD = 'div[class*="lifecycleCard"]';
const DISCLOSURE_SUMMARY = 'What is not yet measurable';

// The variant site is only built by the coverage run; outside it the base path
// does not exist and the ordinary page still carries every collection.
const describeCoverage =
  process.env.E2E_COVERAGE === '1' ? test.describe : test.describe.skip;

const COVERAGE_ENV = { E2E_COVERAGE: '1' };
const VARIANT_ENV = { E2E_COVERAGE: '1', E2E_COVERAGE_VARIANT: '1' };

// Read both documents through the overlay rather than hard-coding labels or
// counts, so an edited overlay fails here instead of leaving a test that
// asserts nothing.
const coverageData = loadSiteData('metrics.json', COVERAGE_ENV);
const variantData = loadSiteData('metrics.json', VARIANT_ENV);

const chartSection = (page, id) =>
  page.locator(`section[aria-labelledby="${id}-title"]`);

describeCoverage('a metrics document missing its collections', () => {
  test('the real page has every collection to render', async ({ page }) => {
    // The premise of the whole file: against the data the site ships, all five
    // collections are non-empty, so no fallback is reachable here.
    const lifecycle = coverageData.referenceArchitectureLifecycle;
    expect(lifecycle.cards.length).toBeGreaterThan(0);
    expect(Object.keys(lifecycle.trends).length).toBeGreaterThan(0);
    expect(lifecycle.omitted.length).toBeGreaterThan(0);
    expect(Object.keys(coverageData.series).length).toBeGreaterThan(0);
    expect(Object.keys(coverageData.breakdowns).length).toBeGreaterThan(0);

    await page.goto(METRICS_PATH);

    const section = page.locator(LIFECYCLE);
    await expect(section).toBeVisible();
    await expect(section.locator(CARD)).toHaveCount(lifecycle.cards.length);
    for (const card of lifecycle.cards) {
      await expect(section).toContainText(card.label);
    }

    for (const trend of Object.values(lifecycle.trends)) {
      await expect(section).toContainText(trend.label);
    }

    // The items are counted rather than matched on text: the disclosure is
    // collapsed by default, and tests/e2e/metrics-dashboard.spec.js already
    // owns the open/closed behaviour. A count still distinguishes the mapped
    // list from the empty fallback, which is all this file is about.
    const disclosure = page.locator(`${LIFECYCLE} details`).first();
    await expect(disclosure.getByText(DISCLOSURE_SUMMARY)).toBeVisible();
    await expect(disclosure.locator('p')).toHaveCount(lifecycle.omitted.length);

    for (const id of Object.keys(coverageData.series)) {
      await expect(chartSection(page, id)).toHaveCount(1);
    }
    for (const id of Object.keys(coverageData.breakdowns)) {
      await expect(chartSection(page, id)).toHaveCount(1);
    }
  });

  test('the variant page renders each collection as empty', async ({
    page,
  }) => {
    const lifecycle = variantData.referenceArchitectureLifecycle;
    expect(lifecycle.cards).toBeNull();
    expect(lifecycle.trends).toBeNull();
    expect(lifecycle.omitted).toBeNull();
    expect(variantData.series).toBeNull();
    expect(variantData.breakdowns).toBeNull();

    await page.goto(`${VARIANT_BASE}${METRICS_PATH}`);

    // The page still renders the parts that do not depend on the cleared
    // collections. Without this the rest of the test would pass just as well
    // against a page that failed to render at all.
    await expect(page.getByText(/Last updated/).first()).toBeVisible();
    const section = page.locator(LIFECYCLE);
    await expect(section).toBeVisible();
    await expect(
      section.getByRole('heading', {
        name: 'Reference architecture lifecycle',
      }),
    ).toBeVisible();

    // `trends` is cleared too, so the grid renders nothing: no sparkline, no
    // "No trend data yet" placeholder either, since that arm lives inside
    // Sparkline and Sparkline is never reached. The labels are checked against
    // the *real* document because the variant one no longer carries them.
    const realLifecycle = coverageData.referenceArchitectureLifecycle;
    for (const trend of Object.values(realLifecycle.trends)) {
      await expect(section).not.toContainText(trend.label);
    }
    await expect(section.getByRole('img')).toHaveCount(0);
    await expect(section.getByText('No trend data yet')).toHaveCount(0);

    // Counted rather than matched on text: the card labels are prefixes of the
    // trend labels the real document carries ("Open submissions" against "Open
    // submissions by month"), so a per-label absence assertion would be
    // satisfied by the wrong element.
    await expect(section.locator(CARD)).toHaveCount(0);

    // The <details> element itself is static markup outside the mapped
    // fallback, so it survives; what the fallback removes is every item in it.
    const disclosure = page.locator(`${LIFECYCLE} details`).first();
    await expect(disclosure.getByText(DISCLOSURE_SUMMARY)).toBeVisible();
    await expect(disclosure.locator('p')).toHaveCount(0);

    for (const id of Object.keys(coverageData.series)) {
      await expect(chartSection(page, id)).toHaveCount(0);
    }
    for (const id of Object.keys(coverageData.breakdowns)) {
      await expect(chartSection(page, id)).toHaveCount(0);
    }
  });
});
