// End-to-end coverage for the absent-revision guard of
// src/components/ReferenceArchitectures/index.js, which needs a build of its
// own — and was the first branch in the repository to prove that two builds
// are not enough.
//
// The component reads data/metrics.json at module scope and opens with:
//
//   12  const architectures = metrics?.sources?.architectures;
//   13  if (!architectures?.revision) return null;
//
// The guard is an ordinary shape rather than defensive dead code:
// data/metrics.json is regenerated by `npm run collect:metrics`, and a
// collector run that reaches the architectures source but cannot resolve a
// commit emits the document without a revision. The checked-in file always
// carries one, so no browser test reaches line 13 against the shipped data.
//
// Why this cannot share the variant build. tests/e2e/fixtures/data-variant/
// clears metrics.generatedAt, which is what makes the same component render
// the `: null` arm of its syncDate ternary (line 23) and the `''` arm beside
// it (line 33). Both of those arms live *inside* the guard this overlay
// closes: clearing revision in that build would return at line 13 and take
// lines 14–34 with it, trading the arms the variant exists for against the one
// gained. Nor can an additive overlay reach it — `add` works for a keyed
// collection, where a fixture record renders beside the real ones, and
// sources.architectures.revision is a scalar on a singleton with nothing to
// sit beside.
//
// So it gets tests/e2e/fixtures/data-no-revision/, compiled by
// `npm run build:e2e:coverage` into build/e2e-coverage-no-revision under base
// URL /e2e-coverage-no-revision/. One `docusaurus serve` offers it beside the
// real site and the variant, one Playwright run visits all three, and the
// report unions what each reached — the builds compile the same src/**
// sources, so their scripts fold onto the same lines. See the preamble of
// tests/tools/e2e-data-fixtures.cjs for the mechanism.
//
// The real route is asserted alongside the no-revision one. On its own, an
// assertion that a page has no provenance line passes just as well when the
// page failed to build or the route is wrong; pairing it with the real route
// is what makes the pair evidence that the guard *switched*.
import { test, expect } from '../tools/e2e-coverage.cjs';
import { loadSiteData } from '../tools/e2e-data-fixtures.cjs';

const ARCHITECTURES_PATH = '/architectures';
const NO_REVISION_BASE = '/e2e-coverage-no-revision';
const SECTION_NAME = 'Reference architecture catalog';
const SYNC_STATUS = /Last synced from/;

// The fixture sites are only built by the coverage run; outside it the base
// path does not exist and the ordinary page still carries a revision.
const describeCoverage =
  process.env.E2E_COVERAGE === '1' ? test.describe : test.describe.skip;

const COVERAGE_ENV = { E2E_COVERAGE: '1' };
const NO_REVISION_ENV = {
  E2E_COVERAGE: '1',
  E2E_COVERAGE_BUILD: 'no-revision',
};

// Read through the overlay rather than hard-coding, so an edited overlay fails
// here instead of leaving a test that asserts nothing.
const metrics = loadSiteData('metrics.json', COVERAGE_ENV);
const noRevisionMetrics = loadSiteData('metrics.json', NO_REVISION_ENV);

const sectionOf = (page) => page.getByRole('region', { name: SECTION_NAME });

describeCoverage('an architectures source with no resolved revision', () => {
  test('the real page links the commit it last synced from', async ({
    page,
  }) => {
    // The premise of the whole file: against the data the site ships, the
    // guard below is unreachable.
    expect(metrics.sources.architectures.revision).toBeTruthy();

    await page.goto(ARCHITECTURES_PATH);
    await expect(sectionOf(page)).toBeVisible();
    const syncStatus = page.getByText(SYNC_STATUS);
    await expect(syncStatus).toBeVisible();
    // The short revision is what the guard gates: its presence is the
    // evidence the component got past line 13 rather than merely rendering
    // some paragraph.
    await expect(syncStatus).toContainText(
      metrics.sources.architectures.revision.slice(0, 7),
    );
  });

  test('the no-revision page drops the whole provenance line', async ({
    page,
  }) => {
    expect(noRevisionMetrics.sources.architectures.revision).toBeNull();
    // generatedAt stays present, so this build differs from the variant one
    // in exactly the field under test.
    expect(noRevisionMetrics.generatedAt).toBeTruthy();

    await page.goto(`${NO_REVISION_BASE}${ARCHITECTURES_PATH}`);
    // The route built and served: the catalog count is prose beside
    // SyncStatus in the same section, so it renders either way.
    const section = sectionOf(page);
    await expect(section).toBeVisible();
    await expect(
      section.getByText(/architecture reports from CNCF end users/),
    ).toBeVisible();
    // The guard returning null is the provenance line not existing at all —
    // not an empty paragraph, and not a line that merely lost its date, which
    // is what tests/e2e/data-variants.spec.js pins for the variant build.
    await expect(page.getByText(SYNC_STATUS)).toHaveCount(0);
    await expect(
      section.getByRole('link', { name: 'cncf/architecture' }),
    ).toHaveCount(0);
  });
});
