#!/usr/bin/env node
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { reportAndExit } from './lib/validate-utils.mjs';

// data/members.json is generated by scripts/generate-members.mjs from
// data/architectures/catalog.json and data/awards.json, but it is committed as
// a file in its own right and nothing regenerates it in CI. A hand edit to it
// is therefore never checked against the sources it claims to be derived from,
// and it was the last data file rendered by src/components with no validator
// behind it -- the gap validate-projects-born.mjs closed for <a href> values,
// still open here for <img src>.
//
// `logo` is the field that matters most. src/components/MemberDirectory
// (MemberCard.js, MemberProfile.js) passes it through Docusaurus useBaseUrl(),
// which returns any value carrying a protocol unchanged, so an absolute URL
// reaches the page as a live <img src> that every visitor's browser fetches on
// load -- the third-party beacon that scripts/lib/profile-image.mjs and the
// img-src directive in docusaurus.config.js exist to prevent. Require a
// site-local path instead, and require it to resolve under static/.
//
// URL fields are parsed rather than prefix-tested, the standard checkUrl() in
// validate-projects-born.mjs and checkHttpsUrl() in validate-awards.mjs
// already apply: /^https:\/\// accepts "https://www.cncf.io@evil.example/",
// whose visible prefix and real host disagree.

const staticRoot = fileURLToPath(new URL('../static/', import.meta.url));
const landscapePath = fileURLToPath(
  new URL('../data/enduser-landscape.json', import.meta.url),
);

const REQUIRED_TEXT_FIELDS = ['id', 'name', 'slug'];
const REQUIRED_ARRAY_FIELDS = [
  'industries',
  'projects',
  'architectures',
  'awards',
  'sourceAttribution',
];
const AWARD_URL_FIELDS = ['announcementUrl', 'caseStudyUrl', 'talkUrl'];
const MEMBERSHIP_STATUSES = new Set([
  'member',
  'contributor',
  'member-and-contributor',
  'unknown',
]);

/**
 * Require an https URL that resolves to the host it appears to name.
 *
 * @param {Array<Object>} errors
 * @param {string} path
 * @param {string} field
 * @param {unknown} value
 */
function checkHttpsUrl(errors, path, field, value) {
  if (typeof value !== 'string' || !value.trim()) {
    errors.push({
      path,
      severity: 'error',
      message: `${field} must be a non-empty string`,
    });
    return;
  }

  let parsed;
  try {
    parsed = new URL(value.trim());
  } catch {
    errors.push({
      path,
      severity: 'error',
      message: `${field} must be an absolute https URL: ${JSON.stringify(value)}`,
    });
    return;
  }

  if (parsed.protocol !== 'https:') {
    errors.push({
      path,
      severity: 'error',
      message: `${field} must use https, got ${parsed.protocol}`,
    });
    return;
  }

  if (parsed.username || parsed.password) {
    errors.push({
      path,
      severity: 'error',
      message: `${field} must not carry a userinfo component, which only disguises the real host (${parsed.hostname})`,
    });
  }
}

/**
 * Require a logo that the site serves itself.
 *
 * useBaseUrl() returns anything with a protocol unchanged, and a
 * protocol-relative "//host/x.svg" inherits https and loads off-site just the
 * same, so both have to fail here rather than reach an <img src>.
 *
 * @param {Array<Object>} errors
 * @param {string} path
 * @param {unknown} value
 */
function checkLogo(errors, path, value) {
  if (value === null || value === undefined) return;

  if (typeof value !== 'string' || !value.trim()) {
    errors.push({
      path,
      severity: 'error',
      message: 'logo must be null or a non-empty site-local path',
    });
    return;
  }

  const logo = value.trim();

  if (logo.startsWith('//') || /^[a-z][a-z0-9+.-]*:/i.test(logo)) {
    errors.push({
      path,
      severity: 'error',
      message: `logo must be a site-local path, not a remote reference that every visitor's browser fetches on page load: ${JSON.stringify(logo)}`,
    });
    return;
  }

  if (!logo.startsWith('/')) {
    errors.push({
      path,
      severity: 'error',
      message: `logo must start with "/" so it resolves against the site root: ${JSON.stringify(logo)}`,
    });
    return;
  }

  if (logo.split('/').includes('..')) {
    errors.push({
      path,
      severity: 'error',
      message: `logo must not traverse out of the static directory: ${JSON.stringify(logo)}`,
    });
    return;
  }

  if (!existsSync(join(staticRoot, logo.replace(/^\//, '')))) {
    errors.push({
      path,
      severity: 'error',
      message: `logo does not exist under static/: ${logo}`,
    });
  }
}

const data = JSON.parse(
  readFileSync(new URL('../data/members.json', import.meta.url)),
);
const errors = [];
const landscape = existsSync(landscapePath)
  ? JSON.parse(readFileSync(landscapePath, 'utf8'))
  : null;
const landscapeBySourceId = new Map(
  (landscape?.records || []).map((record) => [record.sourceId, record]),
);

const members = Array.isArray(data?.members) ? data.members : [];
if (!members.length) {
  errors.push({
    path: 'members.json',
    severity: 'error',
    message: 'members must be a non-empty array',
  });
}

const ids = new Set();
for (const member of members) {
  const path = typeof member?.id === 'string' ? member.id : 'unknown';

  for (const field of REQUIRED_TEXT_FIELDS) {
    const value = member?.[field];
    if (typeof value !== 'string' || !value.trim()) {
      errors.push({
        path,
        severity: 'error',
        message: `${field} must be a non-empty string`,
      });
    }
  }

  if (typeof member?.id === 'string' && ids.has(member.id)) {
    errors.push({ path, severity: 'error', message: 'duplicate id' });
  }
  ids.add(member?.id);

  for (const field of REQUIRED_ARRAY_FIELDS) {
    if (!Array.isArray(member?.[field])) {
      errors.push({
        path,
        severity: 'error',
        message: `${field} must be an array`,
      });
    }
  }

  checkLogo(errors, path, member?.logo);

  for (const entry of Array.isArray(member?.architectures)
    ? member.architectures
    : []) {
    checkHttpsUrl(errors, path, 'architectures[].sourceUrl', entry?.sourceUrl);
  }

  for (const award of Array.isArray(member?.awards) ? member.awards : []) {
    for (const field of AWARD_URL_FIELDS) {
      // A null award URL is the generator's own "not published" marker and the
      // components guard on it before rendering a link.
      if (award?.[field] === null || award?.[field] === undefined) continue;
      checkHttpsUrl(errors, path, `awards[].${field}`, award[field]);
    }
  }

  for (const url of Array.isArray(member?.sourceAttribution)
    ? member.sourceAttribution
    : []) {
    checkHttpsUrl(errors, path, 'sourceAttribution[]', url);
  }

  // Evaluate the null-member fallback once: inline `(member || {})` on each
  // `in` test leaves the later fallbacks unreachable, because a null member
  // already short-circuits the first test.
  const membershipFields = member || {};
  const hasMembershipFields =
    'membershipStatus' in membershipFields ||
    'membershipSources' in membershipFields;
  if (
    landscape &&
    (!('membershipStatus' in membershipFields) ||
      !('membershipSources' in membershipFields))
  ) {
    errors.push({
      path,
      severity: 'error',
      message:
        'landscape-backed output requires membershipStatus and membershipSources',
    });
  }
  if (hasMembershipFields) {
    const status = member?.membershipStatus;
    if (!MEMBERSHIP_STATUSES.has(status)) {
      errors.push({
        path,
        severity: 'error',
        message: `membershipStatus must be one of ${[
          ...MEMBERSHIP_STATUSES,
        ].join(', ')}`,
      });
    }
    if (!Array.isArray(member?.membershipSources)) {
      errors.push({
        path,
        severity: 'error',
        message: 'membershipSources must be an array',
      });
    }
    const sources = Array.isArray(member?.membershipSources)
      ? member.membershipSources
      : [];
    const roles = new Set();
    for (const [index, source] of sources.entries()) {
      const sourcePath = `${path}.membershipSources[${index}]`;
      for (const field of [
        'sourceId',
        'role',
        'sourceName',
        'category',
        'subcategory',
        'sourceUrl',
      ]) {
        if (typeof source?.[field] !== 'string' || !source[field].trim()) {
          errors.push({
            path: sourcePath,
            severity: 'error',
            message: `${field} must be a non-empty string`,
          });
        }
      }
      if (!['member', 'contributor'].includes(source?.role)) {
        errors.push({
          path: sourcePath,
          severity: 'error',
          message: 'role must be member or contributor',
        });
      } else {
        roles.add(source.role);
      }
      checkHttpsUrl(errors, sourcePath, 'sourceUrl', source?.sourceUrl);
      if (source?.localLogo !== null && source?.localLogo !== undefined) {
        checkLogo(errors, sourcePath, source.localLogo);
      }
      if (landscape) {
        const sourceRecord = landscapeBySourceId.get(source?.sourceId);
        if (!sourceRecord) {
          errors.push({
            path: sourcePath,
            severity: 'error',
            message: 'membership source is absent from enduser-landscape.json',
          });
        } else {
          for (const field of [
            ['role', 'sourceRole'],
            ['sourceName', 'sourceName'],
            ['category', 'category'],
            ['subcategory', 'subcategory'],
          ]) {
            if (
              field[1] in sourceRecord &&
              source?.[field[0]] !== sourceRecord[field[1]]
            ) {
              errors.push({
                path: sourcePath,
                severity: 'error',
                message: `${field[0]} does not match the pinned landscape record`,
              });
            }
          }
          for (const field of ['homepageUrl', 'joined', 'localLogo']) {
            if (
              field in sourceRecord &&
              (source?.[field] ?? null) !== (sourceRecord[field] ?? null)
            ) {
              errors.push({
                path: sourcePath,
                severity: 'error',
                message: `${field} does not match the pinned landscape record`,
              });
            }
          }
          if (source?.sourceUrl !== landscape.source?.sourceUrl) {
            errors.push({
              path: sourcePath,
              severity: 'error',
              message: 'sourceUrl does not match landscape provenance',
            });
          }
        }
      }
    }
    if (status === 'unknown' && sources.length > 0) {
      errors.push({
        path,
        severity: 'error',
        message: 'unknown membership must not carry membershipSources',
      });
    }
    if (
      status === 'member' &&
      (!roles.has('member') || roles.has('contributor'))
    ) {
      errors.push({
        path,
        severity: 'error',
        message: 'member status must carry only member sources',
      });
    }
    if (
      status === 'contributor' &&
      (!roles.has('contributor') || roles.has('member'))
    ) {
      errors.push({
        path,
        severity: 'error',
        message: 'contributor status must carry only contributor sources',
      });
    }
    if (
      status === 'member-and-contributor' &&
      (!roles.has('member') || !roles.has('contributor'))
    ) {
      errors.push({
        path,
        severity: 'error',
        message: 'member-and-contributor status must carry both source roles',
      });
    }
  }
}

if (landscape) {
  const expected = new Set(
    (landscape.records || [])
      .filter((record) => record.included)
      .map((record) => record.sourceId),
  );
  const represented = [];
  for (const member of members) {
    for (const source of member?.membershipSources || []) {
      represented.push(source?.sourceId);
    }
  }
  const representedSet = new Set(represented);
  if (represented.length !== representedSet.size) {
    errors.push({
      path: 'members.json',
      severity: 'error',
      message: 'membership source IDs must be unique',
    });
  }
  const missing = [...expected].filter((id) => !representedSet.has(id));
  const unexpected = [...representedSet].filter((id) => !expected.has(id));
  if (missing.length || unexpected.length) {
    errors.push({
      path: 'members.json',
      severity: 'error',
      message: `membership source ID set mismatch (missing: ${missing.join(', ') || 'none'}; unexpected: ${unexpected.join(', ') || 'none'})`,
    });
  }
  if (
    data.sources?.landscape?.revision !== landscape.source?.revision ||
    data.sources?.landscape?.sourceUrl !== landscape.source?.sourceUrl
  ) {
    errors.push({
      path: 'members.json.sources.landscape',
      severity: 'error',
      message: 'landscape provenance must match enduser-landscape.json',
    });
  }
}

reportAndExit(errors, 'members');
console.log(`Validated ${members.length} members`);
