#!/usr/bin/env node
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { reportAndExit } from './lib/validate-utils.mjs';

// data/members.json is generated by scripts/generate-members.mjs from
// data/architectures/catalog.json and data/awards.json, but it is committed as
// a file in its own right and nothing regenerates it in CI. A hand edit to it
// is therefore never checked against the sources it claims to be derived from,
// and it was the last data file rendered by src/components with no validator
// behind it -- the gap validate-projects-born.mjs closed for <a href> values,
// still open here for <img src>.
//
// `logo` is the field that matters most. src/components/MemberDirectory
// (MemberCard.js, MemberProfile.js) passes it through Docusaurus useBaseUrl(),
// which returns any value carrying a protocol unchanged, so an absolute URL
// reaches the page as a live <img src> that every visitor's browser fetches on
// load -- the third-party beacon that scripts/lib/profile-image.mjs and the
// img-src directive in docusaurus.config.js exist to prevent. Require a
// site-local path instead, and require it to resolve under static/.
//
// URL fields are parsed rather than prefix-tested, the standard checkUrl() in
// validate-projects-born.mjs and checkHttpsUrl() in validate-awards.mjs
// already apply: /^https:\/\// accepts "https://www.cncf.io@evil.example/",
// whose visible prefix and real host disagree.

const staticRoot = fileURLToPath(new URL('../static/', import.meta.url));

const REQUIRED_TEXT_FIELDS = ['id', 'name', 'slug'];
const REQUIRED_ARRAY_FIELDS = [
  'industries',
  'projects',
  'architectures',
  'awards',
  'sourceAttribution',
];
const AWARD_URL_FIELDS = ['announcementUrl', 'caseStudyUrl', 'talkUrl'];

/**
 * Require an https URL that resolves to the host it appears to name.
 *
 * @param {Array<Object>} errors
 * @param {string} path
 * @param {string} field
 * @param {unknown} value
 */
function checkHttpsUrl(errors, path, field, value) {
  if (typeof value !== 'string' || !value.trim()) {
    errors.push({
      path,
      severity: 'error',
      message: `${field} must be a non-empty string`,
    });
    return;
  }

  let parsed;
  try {
    parsed = new URL(value.trim());
  } catch {
    errors.push({
      path,
      severity: 'error',
      message: `${field} must be an absolute https URL: ${JSON.stringify(value)}`,
    });
    return;
  }

  if (parsed.protocol !== 'https:') {
    errors.push({
      path,
      severity: 'error',
      message: `${field} must use https, got ${parsed.protocol}`,
    });
    return;
  }

  if (parsed.username || parsed.password) {
    errors.push({
      path,
      severity: 'error',
      message: `${field} must not carry a userinfo component, which only disguises the real host (${parsed.hostname})`,
    });
  }
}

/**
 * Require a logo that the site serves itself.
 *
 * useBaseUrl() returns anything with a protocol unchanged, and a
 * protocol-relative "//host/x.svg" inherits https and loads off-site just the
 * same, so both have to fail here rather than reach an <img src>.
 *
 * @param {Array<Object>} errors
 * @param {string} path
 * @param {unknown} value
 */
function checkLogo(errors, path, value) {
  if (value === null || value === undefined) return;

  if (typeof value !== 'string' || !value.trim()) {
    errors.push({
      path,
      severity: 'error',
      message: 'logo must be null or a non-empty site-local path',
    });
    return;
  }

  const logo = value.trim();

  if (logo.startsWith('//') || /^[a-z][a-z0-9+.-]*:/i.test(logo)) {
    errors.push({
      path,
      severity: 'error',
      message: `logo must be a site-local path, not a remote reference that every visitor's browser fetches on page load: ${JSON.stringify(logo)}`,
    });
    return;
  }

  if (!logo.startsWith('/')) {
    errors.push({
      path,
      severity: 'error',
      message: `logo must start with "/" so it resolves against the site root: ${JSON.stringify(logo)}`,
    });
    return;
  }

  if (logo.split('/').includes('..')) {
    errors.push({
      path,
      severity: 'error',
      message: `logo must not traverse out of the static directory: ${JSON.stringify(logo)}`,
    });
    return;
  }

  if (!existsSync(join(staticRoot, logo.replace(/^\//, '')))) {
    errors.push({
      path,
      severity: 'error',
      message: `logo does not exist under static/: ${logo}`,
    });
  }
}

const data = JSON.parse(
  readFileSync(new URL('../data/members.json', import.meta.url)),
);
const errors = [];

const members = Array.isArray(data?.members) ? data.members : [];
if (!members.length) {
  errors.push({
    path: 'members.json',
    severity: 'error',
    message: 'members must be a non-empty array',
  });
}

const ids = new Set();
for (const member of members) {
  const path = typeof member?.id === 'string' ? member.id : 'unknown';

  for (const field of REQUIRED_TEXT_FIELDS) {
    const value = member?.[field];
    if (typeof value !== 'string' || !value.trim()) {
      errors.push({
        path,
        severity: 'error',
        message: `${field} must be a non-empty string`,
      });
    }
  }

  if (typeof member?.id === 'string' && ids.has(member.id)) {
    errors.push({ path, severity: 'error', message: 'duplicate id' });
  }
  ids.add(member?.id);

  for (const field of REQUIRED_ARRAY_FIELDS) {
    if (!Array.isArray(member?.[field])) {
      errors.push({
        path,
        severity: 'error',
        message: `${field} must be an array`,
      });
    }
  }

  checkLogo(errors, path, member?.logo);

  for (const entry of Array.isArray(member?.architectures)
    ? member.architectures
    : []) {
    checkHttpsUrl(errors, path, 'architectures[].sourceUrl', entry?.sourceUrl);
  }

  for (const award of Array.isArray(member?.awards) ? member.awards : []) {
    for (const field of AWARD_URL_FIELDS) {
      // A null award URL is the generator's own "not published" marker and the
      // components guard on it before rendering a link.
      if (award?.[field] === null || award?.[field] === undefined) continue;
      checkHttpsUrl(errors, path, `awards[].${field}`, award[field]);
    }
  }

  for (const url of Array.isArray(member?.sourceAttribution)
    ? member.sourceAttribution
    : []) {
    checkHttpsUrl(errors, path, 'sourceAttribution[]', url);
  }
}

reportAndExit(errors, 'members');
console.log(`Validated ${members.length} members`);
